import {
  Cloud,
  Waves,
  House,
  Leaf,
  Apple,
  PawPrint,
  Trees,
  Plane,
  Music,
  Orbit,
  Sailboat,
  Compass,
  Globe,
  Telescope,
  Landmark,
  Bone,
  Coffee,
  Shirt,
  Palette,
  Shapes,
  Citrus,
  Carrot,
  CookingPot,
  CakeSlice,
  Tractor,
  Bird,
  Bug,
  Flower2,
  GraduationCap,
  BriefcaseBusiness,
  Building2,
  Bus,
  Dumbbell,
  ToyBrick,
  Paintbrush,
  BookOpen,
  CloudSun,
  CalendarDays,
  Mountain,
  Droplets,
  TreePalm,
  Cat,
  Snowflake,
  Sun,
  Accessibility,
  Eye,
  Heart,
  Handshake,
  Star,
  Gem,
  FlaskConical,
  Atom,
  Cpu,
  Lightbulb,
  DraftingCompass,
  Ship,
  Sprout,
  Calculator,
  ScrollText,
  Tent,
  type LucideIcon,
} from 'lucide-react';

// Every authored theme has an explicit local vector mark, shared by campaign
// and catalogue. No generic fallback silently stands in for missing artwork.
export const PUZZLE_ICONS: Record<string, LucideIcon> = {
  cielo: Cloud,
  agua: Waves,
  hogar: House,
  naturaleza: Leaf,
  huerto: Apple,
  animales: PawPrint,
  bosque: Trees,
  viaje: Plane,
  musica: Music,
  universo: Orbit,
  oceano: Sailboat,
  aventura: Compass,
  planeta: Globe,
  exploracion: Telescope,
  arqueologia: Landmark,
  prehistoria: Bone,
  desayuno: Coffee,
  ropa: Shirt,
  colores: Palette,
  formas: Shapes,
  frutero: Citrus,
  verduras: Carrot,
  cocina: CookingPot,
  dulces: CakeSlice,
  granja: Tractor,
  aves: Bird,
  insectos: Bug,
  jardin: Flower2,
  escuela: GraduationCap,
  oficios: BriefcaseBusiness,
  ciudad: Building2,
  transporte: Bus,
  deportes: Dumbbell,
  juguetes: ToyBrick,
  arte: Paintbrush,
  lectura: BookOpen,
  clima: CloudSun,
  estaciones: CalendarDays,
  montanas: Mountain,
  rios: Droplets,
  selva: TreePalm,
  sabana: Cat,
  polar: Snowflake,
  desierto: Sun,
  cuerpo: Accessibility,
  sentidos: Eye,
  emociones: Heart,
  amistad: Handshake,
  astronomia: Star,
  geologia: Gem,
  quimica: FlaskConical,
  fisica: Atom,
  tecnologia: Cpu,
  inventos: Lightbulb,
  arquitectura: DraftingCompass,
  navegacion: Ship,
  ecologia: Sprout,
  matematicas: Calculator,
  mitologia: ScrollText,
  expedicion: Tent,
};
export default function PuzzleIcon({ id }: { id: string }) {
  const Icon = PUZZLE_ICONS[id];
  if (!Icon) throw Error(`Missing theme icon: ${id}`);
  return <Icon className="puzzle-icon" aria-hidden="true" />;
}
