import type { Language } from './preferences.ts';
const es = {
  hint: 'Pista',
  watch: 'Ver anuncio · 1 letra',
  later: 'Ahora no',
  offer: 'Un anuncio para revelar la siguiente letra de esta palabra:',
  help: 'Ve un anuncio para revelar la siguiente letra de una palabra. Las pistas desaparecen al salir de la partida.',
  transitions:
    'Puede aparecer un anuncio al continuar después de completar un nivel. No aparece mientras eliges letras. Puedes jugar sin conexión; las pistas con anuncio requieren internet.',
  unavailable:
    'No hay un anuncio disponible ahora. Puedes seguir jugando y probar más tarde.',
  web: 'Los anuncios y las pistas recompensadas no están disponibles en esta versión de navegador.',
  cancelled: 'Anuncio cerrado sin recompensa. Tu avance sigue igual.',
  rewarded: 'Una letra revelada. Sigue el recorrido marcado.',
  storage: 'No se pudo activar la pista. Puedes seguir jugando.',
  complete:
    'Recorrido revelado: selecciona la palabra para pasar a la siguiente pista.',
  busy: 'Un momento…',
  test: 'Anuncios de prueba',
  privacy: 'Opciones de privacidad de anuncios',
  report:
    'Para denunciar un anuncio, abre su icono de información o AdChoices y elige la opción de informar.',
  path: 'Recorrido de la pista',
  show: 'Mostrar recorrido',
};
export type AdCopy = typeof es;
const keys = Object.keys(es) as (keyof AdCopy)[];
function row(values: string[]): AdCopy {
  if (values.length !== keys.length) throw Error('Incomplete ad translation');
  return Object.fromEntries(keys.map((key, i) => [key, values[i]])) as AdCopy;
}
export const AD_COPY: Record<Language, AdCopy> = {
  es,
  en: row([
    'Hint',
    'Watch ad · 1 letter',
    'Not now',
    'Complete an ad to reveal the next letter of this word:',
    'Watch an ad to reveal the next letter of a word. Hints disappear when you leave the game.',
    'An ad may appear when you continue after completing a level. It never appears while selecting letters. You can play offline; ad hints require internet.',
    'No ad is available right now. Keep playing and try again later.',
    'Ads and rewarded hints are unavailable in this browser version.',
    'Ad closed without a reward. Your progress is unchanged.',
    'One letter revealed. Follow the marked path.',
    'The hint could not be activated. You can keep playing.',
    'Path revealed: select the word before requesting the next hint.',
    'One moment…',
    'Test ads',
    'Ad privacy options',
    'To report an ad, open its information or AdChoices icon and choose the report option.',
    'Hint path',
    'Show path',
  ]),
  ca: row([
    'Pista',
    'Veure anunci · 1 lletra',
    'Ara no',
    'Completa un anunci per revelar la lletra següent d’aquesta paraula:',
    'Mira un anunci per revelar la lletra següent d’una paraula. Les pistes desapareixen en sortir de la partida.',
    'Pot aparèixer un anunci en continuar després de completar un nivell. No apareix mentre tries lletres. Pots jugar sense connexió; les pistes amb anunci necessiten internet.',
    'Ara no hi ha cap anunci disponible. Pots continuar jugant i tornar-ho a provar més tard.',
    'Els anuncis i les pistes amb recompensa no estan disponibles en aquesta versió de navegador.',
    'Anunci tancat sense recompensa. El progrés no ha canviat.',
    'Una lletra revelada. Segueix el recorregut marcat.',
    'No s’ha pogut activar la pista. Pots continuar jugant.',
    'Recorregut revelat: selecciona la paraula abans de demanar la pista següent.',
    'Un moment…',
    'Anuncis de prova',
    'Opcions de privadesa dels anuncis',
    'Per denunciar un anunci, obre’n la icona d’informació o AdChoices i tria l’opció d’informar.',
    'Recorregut de la pista',
    'Mostrar recorregut',
  ]),
  fr: row([
    'Indice',
    'Voir une pub · 1 lettre',
    'Pas maintenant',
    'Terminez une publicité pour révéler la prochaine lettre de ce mot :',
    'Regardez une publicité pour révéler la prochaine lettre d’un mot. Les indices disparaissent en quittant la partie.',
    'Une publicité peut apparaître lorsque vous continuez après un niveau terminé, jamais pendant la sélection des lettres. Vous pouvez jouer hors ligne ; les indices publicitaires nécessitent internet.',
    'Aucune publicité disponible pour le moment. Continuez à jouer et réessayez plus tard.',
    'Les publicités et les indices récompensés ne sont pas disponibles dans cette version navigateur.',
    'Publicité fermée sans récompense. Votre progression reste inchangée.',
    'Une lettre révélée. Suivez le parcours indiqué.',
    'Impossible d’activer l’indice. Vous pouvez continuer à jouer.',
    'Parcours révélé : sélectionnez le mot avant de demander le prochain indice.',
    'Un instant…',
    'Publicités de test',
    'Confidentialité des publicités',
    'Pour signaler une publicité, ouvrez son icône d’information ou AdChoices et choisissez l’option de signalement.',
    'Parcours de l’indice',
    'Afficher le parcours',
  ]),
  de: row([
    'Hinweis',
    'Werbung ansehen · 1 Buchstabe',
    'Jetzt nicht',
    'Sieh dir eine Werbung vollständig an, um den nächsten Buchstaben dieses Wortes aufzudecken:',
    'Sieh dir eine Werbung an, um den nächsten Buchstaben eines Wortes aufzudecken. Hinweise verschwinden beim Verlassen der Partie.',
    'Beim Weitergehen nach einem abgeschlossenen Level kann Werbung erscheinen, niemals während der Buchstabenauswahl. Du kannst offline spielen; Werbehinweise benötigen Internet.',
    'Momentan ist keine Werbung verfügbar. Spiele weiter und versuche es später erneut.',
    'Werbung und belohnte Hinweise sind in dieser Browserversion nicht verfügbar.',
    'Werbung ohne Belohnung geschlossen. Dein Fortschritt bleibt erhalten.',
    'Ein Buchstabe aufgedeckt. Folge dem markierten Pfad.',
    'Der Hinweis konnte nicht aktiviert werden. Du kannst weiterspielen.',
    'Pfad aufgedeckt: Wähle das Wort aus, bevor du den nächsten Hinweis anforderst.',
    'Einen Moment…',
    'Testwerbung',
    'Datenschutzoptionen für Werbung',
    'Um Werbung zu melden, öffne ihr Info- oder AdChoices-Symbol und wähle die Meldeoption.',
    'Hinweispfad',
    'Pfad anzeigen',
  ]),
  it: row([
    'Indizio',
    'Guarda annuncio · 1 lettera',
    'Non ora',
    'Completa un annuncio per rivelare la lettera successiva di questa parola:',
    'Guarda un annuncio per rivelare la lettera successiva di una parola. Gli indizi scompaiono quando esci dalla partita.',
    'Può apparire un annuncio quando continui dopo aver completato un livello, mai mentre scegli le lettere. Puoi giocare offline; gli indizi con annuncio richiedono internet.',
    'Nessun annuncio disponibile al momento. Continua a giocare e riprova più tardi.',
    'Annunci e indizi con ricompensa non sono disponibili in questa versione browser.',
    'Annuncio chiuso senza ricompensa. I progressi non cambiano.',
    'Una lettera rivelata. Segui il percorso evidenziato.',
    'Impossibile attivare l’indizio. Puoi continuare a giocare.',
    'Percorso rivelato: seleziona la parola prima di chiedere un altro indizio.',
    'Un momento…',
    'Annunci di prova',
    'Opzioni privacy degli annunci',
    'Per segnalare un annuncio, apri la sua icona informazioni o AdChoices e scegli l’opzione di segnalazione.',
    'Percorso dell’indizio',
    'Mostra percorso',
  ]),
  pt: row([
    'Dica',
    'Ver anúncio · 1 letra',
    'Agora não',
    'Conclui um anúncio para revelar a próxima letra desta palavra:',
    'Vê um anúncio para revelar a próxima letra de uma palavra. As dicas desaparecem ao sair da partida.',
    'Pode aparecer um anúncio ao continuar depois de concluir um nível, nunca durante a seleção de letras. Podes jogar sem ligação; as dicas com anúncio precisam de internet.',
    'Não há anúncios disponíveis agora. Continua a jogar e tenta mais tarde.',
    'Os anúncios e as dicas com recompensa não estão disponíveis nesta versão de navegador.',
    'Anúncio fechado sem recompensa. O progresso mantém-se.',
    'Uma letra revelada. Segue o percurso marcado.',
    'Não foi possível ativar a dica. Podes continuar a jogar.',
    'Percurso revelado: seleciona a palavra antes de pedir a próxima dica.',
    'Um momento…',
    'Anúncios de teste',
    'Opções de privacidade dos anúncios',
    'Para denunciar um anúncio, abre o respetivo ícone de informação ou AdChoices e escolhe a opção de denúncia.',
    'Percurso da dica',
    'Mostrar percurso',
  ]),
  tr: row([
    'İpucu',
    'Reklam izle · 1 harf',
    'Şimdi değil',
    'Bu kelimenin sıradaki harfini açmak için bir reklamı tamamla:',
    'Bir kelimenin sıradaki harfini açmak için reklam izle. Oyundan çıkınca ipuçları silinir.',
    'Bir seviyeyi tamamladıktan sonra devam ederken reklam çıkabilir; harf seçerken çıkmaz. Çevrimdışı oynayabilirsin; reklamlı ipuçları internet gerektirir.',
    'Şu anda reklam yok. Oynamaya devam edip daha sonra tekrar deneyebilirsin.',
    'Bu tarayıcı sürümünde reklamlar ve ödüllü ipuçları kullanılamıyor.',
    'Reklam ödül alınmadan kapatıldı. İlerlemen değişmedi.',
    'Bir harf açıldı. İşaretli yolu izle.',
    'İpucu etkinleştirilemedi. Oynamaya devam edebilirsin.',
    'Yol açıldı: sonraki ipucundan önce kelimeyi seç.',
    'Bir dakika…',
    'Test reklamları',
    'Reklam gizlilik seçenekleri',
    'Bir reklamı bildirmek için bilgi veya AdChoices simgesini açıp bildirme seçeneğini seç.',
    'İpucu yolu',
    'Yolu göster',
  ]),
  ar: row([
    'تلميح',
    'شاهد إعلانًا · حرف واحد',
    'ليس الآن',
    'أكمل إعلانًا لكشف الحرف التالي من هذه الكلمة:',
    'شاهد إعلانًا لكشف الحرف التالي من كلمة. تختفي التلميحات عند مغادرة الجولة.',
    'قد يظهر إعلان عند المتابعة بعد إكمال مستوى، ولا يظهر أثناء اختيار الحروف. يمكنك اللعب دون اتصال؛ تلميحات الإعلانات تتطلب الإنترنت.',
    'لا يتوفر إعلان الآن. يمكنك مواصلة اللعب والمحاولة لاحقًا.',
    'الإعلانات والتلميحات بمكافأة غير متاحة في نسخة المتصفح هذه.',
    'أُغلق الإعلان دون مكافأة. لم يتغير تقدمك.',
    'تم كشف حرف. اتبع المسار المحدد.',
    'تعذر تفعيل التلميح. يمكنك مواصلة اللعب.',
    'تم كشف المسار: حدد الكلمة قبل طلب التلميح التالي.',
    'لحظة…',
    'إعلانات اختبار',
    'خيارات خصوصية الإعلانات',
    'للإبلاغ عن إعلان، افتح رمز المعلومات أو AdChoices فيه واختر خيار الإبلاغ.',
    'مسار التلميح',
    'إظهار المسار',
  ]),
  ko: row([
    '힌트',
    '광고 보기 · 한 글자',
    '나중에',
    '광고를 끝까지 보면 이 단어의 다음 글자가 공개됩니다:',
    '광고를 보면 단어의 다음 글자가 공개됩니다. 게임을 나가면 힌트가 사라집니다.',
    '레벨 완료 후 계속할 때 광고가 나올 수 있습니다. 글자를 선택하는 도중에는 나오지 않습니다. 오프라인에서도 플레이할 수 있지만 광고 힌트에는 인터넷이 필요합니다.',
    '지금은 광고가 없습니다. 계속 플레이하고 나중에 다시 시도하세요.',
    '이 브라우저 버전에서는 광고와 보상형 힌트를 사용할 수 없습니다.',
    '보상 없이 광고를 닫았습니다. 진행 상황은 그대로입니다.',
    '한 글자가 공개되었습니다. 표시된 경로를 따라가세요.',
    '힌트를 활성화하지 못했습니다. 계속 플레이할 수 있습니다.',
    '경로가 모두 공개되었습니다. 다음 힌트를 요청하기 전에 단어를 선택하세요.',
    '잠시만요…',
    '테스트 광고',
    '광고 개인정보 옵션',
    '광고를 신고하려면 광고의 정보 또는 AdChoices 아이콘을 열고 신고 옵션을 선택하세요.',
    '힌트 경로',
    '경로 보기',
  ]),
  ja: row([
    'ヒント',
    '広告を見る · 1文字',
    '今はしない',
    '広告を最後まで見ると、この単語の次の文字が表示されます：',
    '広告を見ると単語の次の文字が表示されます。プレイを終了するとヒントは消えます。',
    'レベル完了後に続けるとき、広告が表示されることがあります。文字の選択中には表示されません。オフラインでも遊べますが、広告ヒントにはインターネットが必要です。',
    '現在、広告はありません。ゲームを続けて、後でもう一度お試しください。',
    'このブラウザ版では広告とリワード型ヒントを利用できません。',
    '報酬を受け取らずに広告を閉じました。進行状況は変わりません。',
    '1文字が表示されました。示された経路をたどってください。',
    'ヒントを有効にできませんでした。ゲームは続けられます。',
    '経路がすべて表示されました。次のヒントの前に単語を選択してください。',
    '少々お待ちください…',
    'テスト広告',
    '広告のプライバシー設定',
    '広告を報告するには、広告の情報またはAdChoicesアイコンを開き、報告を選択してください。',
    'ヒントの経路',
    '経路を表示',
  ]),
};
